project:
  type: website
  output-dir: docs

website:
  title: "semantic-nomad"
  navbar:
    left:
      - text: "research"
        href: research.qmd
      - text: "outputs"
        href: portfolio.qmd

format:
  html:
    theme: zephyr